src/Entity/Prestataire.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Persistence\Mapping\ClassMetadata;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\Common\Persistence\ObjectManagerAware;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PrestataireRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Prestataire implements ObjectManagerAware
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;
    /**
     * @var text
     *
     * @ORM\Column( type="text" , nullable=true)
     */
    private $presentation;

    private $em;

    public function injectObjectManager(ObjectManager $objectManager,ClassMetadata $classMetadata)
    {
        $this->em = $objectManager;
    }

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Image", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=true)
     * @Assert\Valid
     */
    private $image;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Tarif", mappedBy="prestataire" , cascade={"persist","remove"} , orphanRemoval=true)
     */
    private $tarif;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Agenda", mappedBy="prestataire" , cascade={"persist","remove"} , orphanRemoval=true)
     */
    private $agenda;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Rdv", mappedBy="prestataire" , cascade={"persist","remove"} , orphanRemoval=true)
     */
    private $rdv;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Localisation")
     * @ORM\JoinColumn(nullable=true)
     */
    private $ville;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Localisation")
     * @ORM\JoinColumn(nullable=true)
     */
    private $commune;

    /**
     * @var text
     *
     * @ORM\Column(type="text" , nullable=true)
     */
    private $adresse;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255 , nullable=true)
     */
    private $email;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Prestataire", mappedBy="parent" , cascade={"persist","remove"} , orphanRemoval=true)
     */
    private $childs;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Prestataire", inversedBy="childs")
     * @ORM\JoinColumn(name="parent_id", referencedColumnName="id", nullable=true)
     */
    private $parent;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255 , nullable=true)
     */
    private $lienFace;

    /**
     * @var string
     *
     * @ORM\Column( type="string", length=255 , nullable=true)
     */
    private $lienTwiter;

    /**
     * @var string
     *
     * @ORM\Column( type="string", length=255 , nullable=true)
     */
    private $lienLinkedin;

    /**
     * @var string
     *
     * @ORM\Column( type="string", length=255 , nullable=true)
     */
    private $longitude;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255 , nullable=true)
     */
    private $latitude;

    /**
     * @var text
     *
     * @ORM\Column(type="text" , nullable=true)
     */
    private $autreInfo;

    /**
     * @var text
     *
     * @ORM\Column( type="text" , nullable=true)
     */
    private $moyenTransport;

    /**
     * @var text
     *
     * @ORM\Column(type="text" , nullable=true)
     */
    private $decrispTarif;

    /**
     * @var text
     *
     * @ORM\Column( type="text" , nullable=true)
     */
    private $commentaire;


    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255 , nullable=true)
     */
    private $langue;

    /**
     * @var boolean
     *
     * @ORM\Column(type="boolean" , nullable=true)
     */
    private $etat;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Entreprise", cascade={"persist","remove"})
     * @ORM\JoinColumn(nullable=true)
     */
    private $entreprise;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Particulier", cascade={"persist","remove"})
     * @ORM\JoinColumn(nullable=true)
     */
    private $particulier;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created;

    /**
     * @ORM\Column(type="datetime")
     */
    private $modified;

    public function __construct()
    {
        $this->tarif = new ArrayCollection();
        $this->agenda = new ArrayCollection();
        $this->childs = new ArrayCollection();
        $this->rdv = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getData()
    {
           if($this->getEntreprise()){
               return $this->getEntreprise();
           }else{
               return $this->getParticulier();
           }
    } 
    public function getNom()
    {
        if($this->getEntreprise()){
            return $this->getEntreprise()->getNom();
        }else{
            return $this->getParticulier()->getNom().' '.$this->getParticulier()->getPrenom();
        }
    }

    public function getLocalisation()
    {
        if($this->getEntreprise()){
            return $this->getEntreprise()->getLocalisation();
        }else{
            return $this->getParticulier()->getLocalisation();
        }
    } 

    public function getTelephone()
    {
        if($this->getEntreprise()){
            return $this->getEntreprise()->getTelephoneContact();
        }else{
            return $this->getParticulier()->getNom().' '.$this->getParticulier()->getTelephone();
        }
    }

    public function getType()
    {
        if($this->getEntreprise()){
            return 'entreprise';
        }else{
            return 'particulier';
        }
    }

    public function getCreated(): ?\DateTimeInterface
    {
        return $this->created;
    }

    public function setCreated(\DateTimeInterface $created): self
    {
        $this->created = $created;

        return $this;
    }

    public function getModified(): ?\DateTimeInterface
    {
        return $this->modified;
    }

    public function setModified(\DateTimeInterface $modified): self
    {
        $this->modified = $modified;

        return $this;
    }

    public function getIdentifiant()
    {
        return $this->encrypt('encrypt',$this->id);
    }
    function encrypt($action, $string) {
        $output = false;
        $encrypt_method = "AES-256-CBC";
        $secret_key = 'ffgd;jhfserfy@!$DCGGgssd';
        $secret_iv = 'ffgd;jhfserfy@@!$DCGGgssd';
        $key = hash('sha256', $secret_key);

        $iv = substr(hash('sha256', $secret_iv), 0, 16);
        if ( $action == 'encrypt' ) {
            $output = openssl_encrypt($string, $encrypt_method, $key, 0, $iv);
            $output = base64_encode($output);
        } else if( $action == 'decrypt' ) {
            $output = openssl_decrypt(base64_decode($string), $encrypt_method, $key, 0, $iv);
        }
        return $output;
    }

    /**
     * @ORM\PrePersist
     */
    public function setCreatedAtValue()
    {
        if($this->id != null){
            $this->modified = new \DateTime();
        }else {
            $this->created = new \DateTime();
            $this->modified = new \DateTime();
        }

    }

    public function getPresentation(): ?string
    {
        return $this->presentation;
    }

    public function setPresentation(string $presentation): self
    {
        $this->presentation = $presentation;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getLienFace(): ?string
    {
        return $this->lienFace;
    }

    public function setLienFace(?string $lienFace): self
    {
        $this->lienFace = $lienFace;

        return $this;
    }

    public function getLienTwiter(): ?string
    {
        return $this->lienTwiter;
    }

    public function setLienTwiter(?string $lienTwiter): self
    {
        $this->lienTwiter = $lienTwiter;

        return $this;
    }

    public function getLienLinkedin(): ?string
    {
        return $this->lienLinkedin;
    }

    public function setLienLinkedin(?string $lienLinkedin): self
    {
        $this->lienLinkedin = $lienLinkedin;

        return $this;
    }

    public function getLongitude(): ?string
    {
        return $this->longitude;
    }

    public function setLongitude(?string $longitude): self
    {
        $this->longitude = $longitude;

        return $this;
    }

    public function getLatitude(): ?string
    {
        return $this->latitude;
    }

    public function setLatitude(?string $latitude): self
    {
        $this->latitude = $latitude;

        return $this;
    }

    public function getAutreInfo(): ?string
    {
        return $this->autreInfo;
    }

    public function setAutreInfo(?string $autreInfo): self
    {
        $this->autreInfo = $autreInfo;

        return $this;
    }

    public function getMoyenTransport(): ?string
    {
        return $this->moyenTransport;
    }

    public function setMoyenTransport(?string $moyenTransport): self
    {
        $this->moyenTransport = $moyenTransport;

        return $this;
    }

    public function getDecrispTarif(): ?string
    {
        return $this->decrispTarif;
    }

    public function setDecrispTarif(?string $decrispTarif): self
    {
        $this->decrispTarif = $decrispTarif;

        return $this;
    }

    public function getCommentaire(): ?string
    {
        return $this->commentaire;
    }

    public function setCommentaire(?string $commentaire): self
    {

src/Form/PrestataireType.php
<?php

namespace App\Form;

use App\Entity\Prestataire;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PrestataireType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('presentation')
            ->add('adresse')
            ->add('email')
            ->add('lienFace')
            ->add('lienTwiter')
            ->add('lienLinkedin')
            ->add('longitude')
            ->add('latitude')
            ->add('autreInfo')
            ->add('moyenTransport')
            ->add('decrispTarif')
            ->add('commentaire')
            ->add('langue')
            ->add('image' , ImageType::class, array( 'required' => false ))
            ->add('etat', ChoiceType::class, array(
                'choices'  => array(
                    'OUI' => 1,
                    'NON' => 0

                ),
            ))
            ->add('tarif', CollectionType::class, array(

                'entry_type'   => TarifType::class,
                'allow_add' => true,
                'allow_delete' => true,

            ))
            ->add('agenda', CollectionType::class, array(

                'entry_type'   => AgendaType::class,
                'allow_add' => true,
                'allow_delete' => true,

            ))
        ;
        if($options['type'] == 'entreprise'){
            $builder
            ->add('entreprise' , EntrepriseType::class )
                ;
        }
        if($options['type'] == 'particulier'){
            $builder
                ->add('particulier' , ParticulierType::class )
            ;
        }
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Prestataire::class,
            'type' => null
        ]);
    }
}

src/Controller/PrestataireController.php
<?php

namespace App\Controller;

use App\Entity\Localisation;
use App\Entity\Prestataire;
use App\Form\PrestataireType;
use App\Repository\PrestataireRepository;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/prestataire")
 */
class PrestataireController extends Controller
{
    /**
     * @Route("/liste/{id}", name="prestataire_index", methods="GET")
     */
    public function index($id = null, PrestataireRepository $prestataireRepository): Response
    {
        if($id){
            $parent = $prestataireRepository->find($id);
            return $this->render('prestataire/index.html.twig', [ 'parent' => $parent, 'type' => 'parent', 'prestataires' => $prestataireRepository->findBy(['parent' => $parent])]);

        }else{
            return $this->render('prestataire/index.html.twig', ['type' => 'null' , 'prestataires' => $prestataireRepository->findBy(['parent' => null])]);

        }

        //dump($prestataireRepository->findAll()[0]->getNom()); die();
        //return $this->render('prestataire/index.html.twig', ['prestataires' => $prestataireRepository->findAll()]);
    }

    /**
     * @Route("/new/{type}/{parent}/{id}", name="prestataire_new", methods="GET|POST")
     */
    public function new($id= null, Request $request, $type , $parent): Response
    {
        $prestataire = new Prestataire();
        $em = $this->getDoctrine()->getManager();
        if($id != null ){
            $prestataire = $em->getRepository(Prestataire::class)->find($id);
        }
        if($parent != "null" ){
            $parent = $em->getRepository(Prestataire::class)->find($parent);
        }
        $villes = $em->getRepository(Localisation::class)->findBy( ['type' => 'ville'] );
        $form = $this->createForm(PrestataireType::class, $prestataire , [ 'type' => $type ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if($request->get('ville')){
                $ville = $em->getRepository(Localisation::class)->find($request->get('ville'));
                if($ville) $prestataire->setVille($ville);
            }
            if($request->get('commune')){
                $commune = $em->getRepository(Localisation::class)->find($request->get('commune'));
                if($commune) $prestataire->setCommune($commune);
            }

            $em = $this->getDoctrine()->getManager();
            foreach ($prestataire->getTarif() as $key => $tarif){
                if($tarif->getPrestataire() ==null) $prestataire->getTarif()[$key]->setPrestataire($prestataire);
            }
            foreach ($prestataire->getAgenda() as $key => $agenda){
                if($agenda->getPrestataire() ==null) $prestataire->getAgenda()[$key]->setPrestataire($prestataire);
            }
            if($parent != "null" && $parent != null) $prestataire->setParent($parent);
            $em->persist($prestataire);
            $em->flush();

            $request->getSession()->getFlashBag()->add('ajout', 'Opération réussie avec succès !');
            return $this->redirectToRoute('prestataire_show' , [ 'id' => $prestataire->getIdentifiant()  ] );
        }

        return $this->render('prestataire/new.html.twig', [
            'prestataire' => $prestataire,
            'type' => $type,
            'villes' => $villes,
            'parent' =>$parent,
            'form' => $form->createView(),
        ]);
    }
    /**
     * @Route("/agendas-prestataire/{prest}", name="prestataire_agendas")
     */
    public function agendas( $prest , Request $request): Response
    {
        if ($content = $request->getContent()) {
            $parametersAsArray = json_decode($content, true);
            $date = new \DateTime($parametersAsArray['date']);
            $em = $this->getDoctrine()->getManager();
            $prestataire = $em->getRepository(Prestataire::class)->find($prest);
           $agendas =  $prestataire->getHeure($date->format('Y-m-d'));
           echo json_encode($agendas);
        }


        die();
    }

    /**
     * @Route("/{id}", name="prestataire_show", methods="GET")
     */
    public function show(Prestataire $prestataire): Response
    {
        return $this->render('prestataire/show.html.twig', ['prestataire' => $prestataire]);
    }

    /**
     * @Route("/{id}/edit", name="prestataire_edit", methods="GET|POST")
     */
    public function edit(Request $request, Prestataire $prestataire): Response
    {
        $form = $this->createForm(PrestataireType::class, $prestataire);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('prestataire_edit', ['id' => $prestataire->getId()]);
        }

        return $this->render('prestataire/edit.html.twig', [
            'prestataire' => $prestataire,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="prestataire_delete", methods="DELETE")
     */
    public function delete(Request $request, Prestataire $prestataire): Response
    {
        if ($this->isCsrfTokenValid('delete'.$prestataire->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($prestataire);
            $em->flush();
        }

        return $this->redirectToRoute('prestataire_index');
    }
}

templates/prestataire/_delete_form.html.twig
<form method="post" action="{{ path('prestataire_delete', {'id': prestataire.identifiant}) }}" >

    <div aria-hidden="true" aria-labelledby="removeModalLabel" class="modal fade" id="removeModalLabel" role="dialog" tabindex="-1">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Confirmation de suppression</h5>
                    <button aria-label="Close" class="close" data-dismiss="modal" type="button"><span aria-hidden="true"> ×</span></button>
                </div>
                <div class="modal-body">
                    <p style="text-align:center" >Voulez-vous vraiment supprimer l'element? </p>
                </div>
                <div class="modal-footer">
                    <input type="hidden" name="_method" value="DELETE">
                    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ prestataire.id) }}">
                    <button class="btn btn-secondary" data-dismiss="modal" type="button"> Annuler</button>
                    <button type='submit' class="btn btn-primary" >Confirmer </button>
                </div>
            </div>
        </div>
    </div>
    </div>
</form>

templates/prestataire/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/prestataire/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Prestataire{% endblock %}

{% block body %}
    <h1>Edit Prestataire</h1>

    {{ include('prestataire/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('prestataire_index') }}">back to list</a>

    {{ include('prestataire/_delete_form.html.twig') }}
{% endblock %}

templates/prestataire/show.html.twig
{% extends 'admin.html.twig' %}

{% block title %}Fiche Prestataire {{ parent() }} {% endblock %}

{% block body %}
    <div class="row">


        <div class="col-12">
            <div class="block  table-block mb-4">
                <div class="block-heading">
                    <h5> </h5>

                    {% if prestataire.parent != null %}
                        <h5>Fiche Prestataire {{prestataire.nom}} (<span style="color:green"> {{ prestataire.parent.nom }}  </span> )</h5>
                    {% else %}
                        <h5>Fiche Prestataire {{prestataire.nom}} </h5>
                    {% endif %}
                </div>

                <div class="row">
                    <div class="col-12" >

                        {% for message in app.session.flashbag.get('ajout') %}

                            <div class="alert alert-success" role="alert">
                                {{ message }}
                            </div>

                        {% endfor %}
                        <div class="row">


                        <div class="col-md-6">

                        <table class="table table-hover record_properties">
                            <tbody>
                            {% if prestataire.image != null %}
                                <tr>
                                    <th scope="row"></th>
                                    <td>
                                        <img src="{{asset(prestataire.image.WebPath)}}" style="height:120px;"> </td>
                                </tr>
                            {% endif %}
                            {% if prestataire.type == 'entreprise' %}

                            <tr>
                                <th>NOM DE L'ENTREPRISE</th>
                                <td>{{ prestataire.entreprise.nom }}</td>
                            </tr>
                                <tr>
                                    <th>NOM DU CONTACT DANS L'ENTREPRISE</th>
                                    <td>{{ prestataire.entreprise.nomContact }}</td>
                                </tr>
                                <tr>
                                    <th>PRENOM DU CONTACT DANS L'ENTREPRISE</th>
                                    <td>{{ prestataire.entreprise.prenomContact }}</td>
                                </tr>
                                <tr>
                                    <th>TELEPHONE DE L'ENTREPRISE</th>
                                    <td>{{ prestataire.entreprise.telephone }}</td>
                                </tr>
                                <tr>
                                    <th>TELEPHONE DU CONTACT DE L'ENTREPRISE</th>
                                    <td>{{ prestataire.entreprise.telephoneContact }}</td>
                                </tr>
                                <tr>
                                    <th>LOCALISATION DE L'ENTREPRISE</th>
                                    <td>{{ prestataire.entreprise.localisation }}</td>
                                </tr>
                            {% else %}
                                <tr>
                                    <th>NOM DU PRESTATAIRE</th>
                                    <td>{{ prestataire.particulier.nom }}</td>
                                </tr>
                                <tr>
                                    <th>PRENOM DU PRESTATAIRE</th>
                                    <td>{{ prestataire.particulier.prenom }}</td>
                                </tr>
                                <tr>
                                    <th>TELEPHONE DU PRESTATAIRE</th>
                                    <td>{{ prestataire.particulier.telephone }}</td>
                                </tr>
                                <tr>
                                    <th>LOCALISATION DU PRESTATAIRE</th>
                                    <td>{{ prestataire.particulier.localisation }}</td>
                                </tr>
                            {% endif %}
                                <tr>
                                    <th>ADRESSE POSTALE</th>
                                    <td>{{ prestataire.adresse }}</td>
                                </tr>
                                <tr>
                                    <th>EMAIL</th>
                                    <td>{{ prestataire.email }}</td>
                                </tr>
                                <tr>
                                    <th>FACEBOOK</th>
                                    <td>{{ prestataire.lienFace }}</td>
                                </tr>
                                <tr>
                                    <th>TWITTER</th>
                                    <td>{{ prestataire.lienTwiter }}</td>
                                </tr>
                                <tr>
                                    <th>LINKEDIN</th>
                                    <td>{{ prestataire.lienLinkedin }}</td>
                                </tr>
                                <tr>
                                    <th>LONGITUDE</th>
                                    <td>{{ prestataire.longitude }}</td>
                                </tr>
                                <tr>
                                    <th>LATITUDE</th>
                                    <td>{{ prestataire.latitude }}</td>
                                </tr>
                                <tr>
                                    <th>LANGUE</th>
                                    <td>{{ prestataire.langue }}</td>
                                </tr>

                                <tr>
                                    <th>ACTIVER LE PRESTATAIRE</th>
                                    <td>
                                        {% if prestataire.etat %}OUI{% else %}NON{% endif %}
                                    </td>
                                </tr>


                                <tr>
                                    <th>PRÉSENTATION</th>
                                    <td>{{ prestataire.presentation|raw }}</td>
                                </tr>




                            </tbody>
                        </table>
                        </div>
                        <div class="col-md-6">
                            <h5 class="panel-title">Tarif du prestataire
                            </h5>
                            <table class="table">
                                <thead>
                                <tr>
                                    <th scope="col">Service</th>
                                    <th scope="col">Consultation</th>
                                </tr>
                                </thead>
                                <tbody>

                                {% for tarif in prestataire.tarif %}
                                    <tr>

                                        <td>{{ tarif.service.libelle }}</td>
                                        <td>{{ tarif.prix }}</td>
                                    </tr>
                                {% endfor %}


                                </tbody>
                            </table>
                            <br>
                            <h5 class="panel-title">Agenda du prestataire
                            </h5>
                            <table class="table">
                                <thead>
                                <tr>
                                    <th scope="col">Jour</th>
                                    <th scope="col">Créno</th>
                                    <th scope="col">Heure Debut</th>
                                    <th scope="col">Heure Fin</th>
                                </tr>
                                </thead>
                                <tbody>

                                {% for agenda in prestataire.agenda %}
                                    <tr>

                                        <td>{{ agenda.jourFrench }}</td>
                                        <td>{{ agenda.creno }}</td>
                                        <td>{{ agenda.heureD|date('H:i') }}</td>
                                        <td>{{ agenda.heureF|date('H:i') }}</td>
                                    </tr>
                                {% endfor %}


                                </tbody>
                            </table>
                            <br>
                            <table class="table table-hover record_properties">
                                <tbody>
                            <tr>
                                <th>AUTRES INFOS</th>
                                <td>{{ prestataire.autreInfo|raw }}</td>
                            </tr> <tr>
                                <th>MOYENS DE TRANSPORT</th>
                                <td>{{ prestataire.moyenTransport|raw }}</td>
                            </tr>
                            <tr>
                                <th>DESCRIPTION TARIF</th>
                                <td>{{ prestataire.decrispTarif|raw }}</td>
                            </tr>
                            <tr>
                                <th>COMMENTAIRE</th>
                                <td>{{ prestataire.commentaire|raw }}</td>
                            </tr>
                            <tr>
                                <th>Date d'ajout</th>
                                <td>{{ prestataire.created ? prestataire.created|localizeddate('full', 'short') : '' }}</td>
                            </tr>
                            <tr>
                                <th>Derniere Modification</th>
                                <td>{{ prestataire.modified ? prestataire.modified|localizeddate('full', 'short') : '' }}</td>
                            </tr>

                            </tbody>
                            </table>
                        </div>
                        </div>

                        <div class="btn-group record_actions">

                            {% if prestataire.parent != null %}
                                <a class="btn btn-inline btn-info" href="{{path('prestataire_index' , {id:prestataire.parent.identifiant } )}}">
                                    <i class="fa fa-chevron-circle-left"></i> Retour
                                </a>

                                <a class="btn btn-inline btn-primary" href="{{path('prestataire_new' , { parent:prestataire.parent.id, id:prestataire.identifiant , type:prestataire.type } )}}">
                                    Modifier <i class="fa fa-edit"></i>
                                </a>
                            {% else %}

                                <a class="btn btn-inline btn-info" href="{{path('prestataire_index')}}">
                                    <i class="fa fa-chevron-circle-left"></i> Retour
                                </a>
                                <a class="btn btn-inline btn-success" href="{{path('prestataire_index' , {id:prestataire.identifiant } )}}">
                                    les prestataires  <i class="fa fa-th-large"></i>
                                </a>

                                <a class="btn btn-inline btn-primary" href="{{path('prestataire_new' , {'parent':'null',id:prestataire.identifiant , type:prestataire.type } )}}">
                                    Modifier <i class="fa fa-edit"></i>
                                </a>
                            {% endif %}


                        </div>



                    </div>

                </div>

            </div>
        </div>

    </div>

    {{ include('prestataire/_delete_form.html.twig') }}

{% endblock %}